version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # Standard AMQP port
      - "15672:15672"  # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest  # Replace with your username
      RABBITMQ_DEFAULT_PASS: guest  # Replace with your password