// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"
)

type Products struct {
	ID                          string    `json:"id"`
	UserID                      string    `json:"user_id"`
	ProductName                 string    `json:"product_name"`
	ProductDescription          string    `json:"product_description"`
	ProductPrice                string    `json:"product_price"`
	ProductUrls                 []string  `json:"product_urls"`
	CompressedProductImagesUrls []string  `json:"compressed_product_images_urls"`
	CreatedAt                   time.Time `json:"created_at"`
}

type Users struct {
	UserID            string    `json:"user_id"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
	FilesOwned        []string  `json:"files_owned"`
}
